import './data.js';
import './create-photo.js';
import './upload-file.js';
import './photos-effect.js';
import './full-img.js';
import './scale-photo.js';
import './valid-hashtags.js';
import './fetch.js';
import './img-filters.js';
import {getData} from './fetch.js';
